### ISSUE TITLE
Domain consumes 100% cpu

### ISSUE THREAD

**Issue by AviorAlong** [vilic/thenfail#9]
![image](https://user-images.githubusercontent.com/18592408/67187261-66a71b80-f41c-11e9-8c56-d0c165b473cd.png)

**Comment by vilicvane** [comment]
flush 只占了很少的 cpu 时间呀，估计不是 thenfail 的问题。

**Comment by AviorAlong** [comment]
> flush 只占了很少的 cpu 时间呀，估计不是 thenfail 的问题。
domain本身就耗资源，而且是作为一个异常处理的模块存在的，请教下thenfail中使用domain的意义是什么
![image](https://user-images.githubusercontent.com/18592408/67384570-faffb280-f5c3-11e9-8440-420aba2a63fa.png)
![image](https://user-images.githubusercontent.com/18592408/67384707-42863e80-f5c4-11e9-85ed-6285ff0742bf.png)

**Comment by vilicvane** [comment]
@AviorAlong 我没印象在 thenfail 里加过 domain 相关的, 仓库里这个版本好像是没有的. 你们用的那个是不是被谁魔改过的?

**Comment by AviorAlong** [comment]
> @AviorAlong 我没印象在 thenfail 里加过 domain 相关的, 仓库里这个版本好像是没有的. 你们用的那个是不是被谁魔改过的?
版本0.2
![image](https://user-images.githubusercontent.com/18592408/67387106-c6422a00-f5c8-11e9-8995-d9e4500b28ee.png)

**Comment by vilicvane** [comment]
没啥印象了, 这一大段以及外面是做类似于 setImeddiate 的操作的吗? 你 Git blame 一下看看是不是我加的.  另外也可以看看如果用新的版本会有类似的问题吗

**Comment by vilicvane** [comment]
好像是, 看到了, 直接把那一大坨 from Q 的换成 setImmediate 试试

**Comment by AviorAlong** [comment]
> 好像是, 看到了, 直接把那一大坨 from Q 的换成 setImmediate 试试
找到问题了
yog-log 这个库打开了thenfail中的domain开关，最终到达某种极限情况，js线程就得不到执行时间，cpu被futex wait 和futex wake （wake总是返回异常）占完了

**Comment by AviorAlong** [comment]
> 好像是, 看到了, 直接把那一大坨 from Q 的换成 setImmediate 试试

找到问题了
yog-log 这个库打开了thenfail中的domain开关，最终到达某种极限情况，js线程就得不到执行时间，cpu被futex wait 和futex wake （wake总是返回异常）占完了

**Comment by vilicvane** [comment]
@AviorAlong 厉害了... 说来 thenfail 还没换掉也是很意外.
